### PR TITLE
Neuroml export

### PR DESCRIPTION
**Pull request by salvadord**

### CODE REVIEW

**Comment by pgleeson** [comment]
@salvadord this wasn't quite ready to be merged into master yet... Some more testing required... I'll hopefully get to this this week.

**Comment by salvadord** [comment]
@pgleeson - ah sorry about that, will release new version when tested; and will check with you next time before merging onto master

**Comment by pgleeson** [comment]
Ok, thanks. Have you changed the way seeds etc. are handled in the recent changes on development? I'm getting different 3D positions for the same netpyne script (see here: https://github.com/OpenSourceBrain/NetPyNEShowcase/blob/master/NetPyNE/HHSmall/HHSmall.py) which sets: 

      simConfig.seeds = {'conn': 1, 'stim': 1, 'loc': 1}

This is also generating strange values for delays, try https://github.com/OpenSourceBrain/NetPyNEShowcase/blob/master/NetPyNE/HHSmall/HH_export.py:


            <connectionWD id="0" preCellId="../PYR/1/CELL_HH_PYR" postCellId="../PYR/0/CELL_HH_PYR" weight="0.005" delay="14.5184015666 ms"/>
            <connectionWD id="1" preCellId="../PYR/2/CELL_HH_PYR" postCellId="../PYR/0/CELL_HH_PYR" weight="0.005" delay="14.5184015666 ms"/>
            <connectionWD id="2" preCellId="../PYR/0/CELL_HH_PYR" postCellId="../PYR/1/CELL_HH_PYR" weight="0.005" delay="14.5184015666 ms"/>
            <connectionWD id="3" preCellId="../PYR/2/CELL_HH_PYR" postCellId="../PYR/1/CELL_HH_PYR" weight="0.005" delay="14.5184015666 ms"/>
            <connectionWD id="4" preCellId="../PYR/0/CELL_HH_PYR" postCellId="../PYR/2/CELL_HH_PYR" weight="0.005" delay="14.5184015666 ms"/>
            <connectionWD id="5" preCellId="../PYR/1/CELL_HH_PYR" postCellId="../PYR/2/CELL_HH_PYR" weight="0.005" delay="14.5184015666 ms"/>

**Comment by salvadord** [comment]
@pgleeson - ah sorry, made small change in sim.id32() func while debugging and forgot to change back :(  -- will release with fix

**Comment by salvadord** [comment]
thanks for pointing this out, should work ok now -- let me know if still have any issues

**Comment by pgleeson** [comment]
Great. That fix worked!

**Pull request merged**
