### PR TITLE
fix plotConn

### LINKED ISSUE #385: pyplot.hold() method deprecated
matplotlib.pyplot.hold() seems deprecated in matplotlib v 3.0.0. so plotConn method is not working in the GUI

### PR DESCRIPTION
**Pull request by rodriguez-facundo**
this closes #385
hold method in matplotlib v3.0.0 seems deprecated. default behaviour would be hold(True)

### CODE REVIEW

**Comment by adrianq** [comment]
@rodriguez-facundo Questions: Currently, we can have any matplot lib version as non-specific version is required (https://github.com/Neurosim-lab/netpyne/blob/development_py3/setup.py). For instance, I have 2.2.3. Should we specify the version (greater than 3.0) in the dependency? Otherwise, what are the implications of removing that line for versions below 3.0?

**Comment by adrianq** [comment]
@rodriguez-facundo Questions: Currently, we can have any matplot lib version as non-specific version is required (https://github.com/Neurosim-lab/netpyne/blob/development_py3/setup.py). For instance, I have 2.2.3. Should we specify the version (greater than 3.0) in the dependency? Otherwise, what are the implications of removing that line for versions below 3.0?

**Comment by adrianq** [comment]
@rodriguez-facundo Questions: Currently, we can have any matplot lib version as non-specific version is required (https://github.com/Neurosim-lab/netpyne/blob/development_py3/setup.py). For instance, I have 2.2.3. Should we specify the version (greater than 3.0) in the dependency? Otherwise, what are the implications of removing that line for versions below 3.0?

**Comment by rodriguez-facundo** [comment]
the problem for me was Casper-Test failing to plot the connectivity matrix. I read that matplotlib 3.0 eliminated that hold method and the behaviour associated with it is now the standard.

**Pull request merged**
