### PR TITLE
Improve randomization (issues #89 #185)

### PR DESCRIPTION
**Pull request by salvadord**
- Replace python random package methods with h.Random() methods (see https://scicomp.stackexchange.com/questions/24916/how-do-i-reliably-generate-random-numbers-in-python-distributed-across-multiple)

- Use Random123() generator with 3 ids where possible to increase independence of streams -- use pre and post gids, user-provided seeds, and id32() func (32-bit hash) of category strings.

- Only use id32() func for strings, or potentially large numbers (e.g. sum of all gids)

- Update examples to use h.Random functions instead of python's (e.g. gauss() -> normal())

- No backward reproducibility

### CODE REVIEW

**Comment by pgleeson** [comment]
Ok, @salvadord, I'll have a look. Note, I had updated the handling of seeds in the jNeuroML -> Neuron export to ensure the same seed for input stimulations in an equivalent network from NML2 to that imported by NetPyNE would produce the same spiking behaviour. I'll have to update that also (and break backward compatibility there too...).

Are you fairly confident this will be the final change?

**Comment by salvadord** [comment]
@pgleeson - fairly, discussed some with robert and bill and seems reasonable -- but let me know if you have different suggestions

**Comment by pgleeson** [comment]
@salvadord do you have a timeline for when you'd like to incorporate these changes (I'd like to update org.neuroml.export at the same time)?

**Comment by salvadord** [comment]
@pgleeson - Bill is teaching netpyne this Saturday at the NEURON summer course, so I wanted to release a version tomorrow that includes some improvements, bug fixes, and the new error checking that Sid has developed. I would like to include the new randomization too -- I need it for my M1 simulations. However if you need more time I can probably run my sims by using netpyne's 'randomizer' branch. Let me know. thx

**Comment by pgleeson** [comment]
@salvadord the randomizer branch seems to not have the latest development changes.. Can you merge the latest from dev to here? I'm checking between the branches:
https://github.com/Neurosim-lab/netpyne/tree/neuroml_export
https://github.com/Neurosim-lab/netpyne/tree/neuroml_export_test_random
and just want the randomizer differences.
I'll try these changes and can open a PR from the latest nml branch tomorrow too.

**Comment by salvadord** [comment]
merged latest dev into randomizer branch. thanks

**Comment by pgleeson** [comment]
@salvadord thanks.

I think it comes down to replacing my impl of generating the seed for Random123 for stims here: 
https://github.com/NeuroML/org.neuroml.export/blob/development/src/main/java/org/neuroml/export/neuron/NeuronWriter.java#L547
with your calculation of it:
https://github.com/Neurosim-lab/netpyne/blob/randomizer/netpyne/network.py#L125

Personally I'd prefer a more explicit calculation of the seed in a separate method with named attributes, e.g. 

    _generate_seed_for_stim(self.rand, source['type'], ... , sim.cfg.seeds['stim'])

    ...
    def _generate_seed_for_stim(rand, stim_type, param1, param2,..., seed)
         rand.Random123(sim.id32('stim_'+stim_type), ... , seed)

Then I can just copy the _generate_seed_for_stim() method to my code and fill in the attrs. The existing method is difficult to reproduce without me using the same internal Netpyne dicts...

Note, of course you use seeds/Random123 elsewhere, but for my purposes, running a pre generated nml2 file structure in netpyne, the only seed that's relevant is the one for the stimulations during the simulation, i.e. sim.cfg.seeds['stim']

**Comment by salvadord** [comment]
sure thats looks good -- I'd prefer to use a more generic func that can be used for all cases (ie. not only stim, but conn, cell locs etc) e.g.
`def _init_randomizer(rand, label, string, param1, parm2, ..., seed):
  if label = 'stim':
    rand.Random123(sim.id32(label+'_'+string), ... , seed)`

or something like that... I have a grant deadline tomorrow too, but will try to do tonite/tomorrow am -- if you need it before, you can give it a go or do just for stim; the function can be modified later on to cover all cases as long as output for stims is equivalent.

**Comment by pgleeson** [comment]
Ok, fine with me to wait a few days before this all gets synced. 

There can certainly be a new dedicated method for the conn/location seed generation too, but I was trying to press for a method for the stim seed generation that explicitly uses named attributes relevant for the stimulation. In your current form you use 


{6: {'pop': 'hh_net', 'cellType': 'hhcell', 'znorm': 0.3, 'ynorm': 0.34, 'cellLabel': 3, 'xnorm': 0.39, 'label': ['hhcell'], 'propList': [], 'y': 34.0, 'x': 39.0, 'cellModel': 'hhcell', 'z': 30.0}}
(1, 6)
1234567
----------------------
poissonFiringSyn
{7: {'pop': 'hh_net', 'cellType': 'hhcell', 'znorm': 0.4, 'ynorm': 0.44, 'cellLabel': 4, 'xnorm': 0.49, 'label': ['hhcell'], 'propList': [], 'y': 44.0, 'x': 49.0, 'cellModel': 'hhcell', 'z': 40.0}}

**Comment by salvadord** [comment]
Note that the format `sim.id32('%d%d'%(len(postCellsTags), sum(postCellsTags))` is only used for netpyne's string-based functions so don't think you need it right now for neuroml. In any case it is just the concatenation of the number of postsyn cells, and the sum of their gids (none of the dict value params are used).

I believe the one that you need is `stim['hRandom'].Random123(sim.id32('stim_'+stim['source']), cell.gid, stim['seed'])` (which you also mention above). In this case it also uses the gid of the postsyn cell targeted by the stim. This is in order to generate independent streams for each postsyn cell. I have replaced that code with a call to the function you suggested:

```
def _init_stim_randomizer(rand, stimType, gid, seed)
     rand.Random123(sim.id32(stimType), gid, seed)
```
Note in netpyne it is also possible to create a population of artificial cells of type NetStim, in which case the gid would correspond to that of the artificial cell (presyn not post).

Let me know if this works for you or there are other cases you need me to change.

I will release a netpyne version, hopefully would like to include the new randomizer stuff.

ps. gonna look at the parallel error now and will update asap

**Comment by salvadord** [comment]
@pgleeson - sorry I have to merge now so its ready for Bill's netpyne tutorial tomorrow am -- wanted to have all the new features, including rand. 
Hope the func I added above solves neuroml issues, but if not I'll just release another version in the next couple days.

**Comment by pgleeson** [comment]
@salvadord I've updated that in my branch and retested everything, and it looks fine now. It took some work to update, but helped reveal some other minor issues, e.g. #232.

I've updated the Neuron export too to use this method: https://github.com/NeuroML/org.neuroml.export/commit/03f57ed6a947b250eae328d6e234b3bd8e360947, and will make a new release of jnml.

All my OSB projects are passing now and about 12 use NetPyNE in the tests: https://travis-ci.org/OpenSourceBrain.

**Comment by salvadord** [comment]
ok great! thanks

**Pull request merged**
