### PR TITLE
fix for pandas 0.24

### PR DESCRIPTION
**Pull request by cliffckerr**
Addresses https://github.com/Neurosim-lab/netpyne/issues/406 but maintains backwards compatibility with pandas 0.23

### CODE REVIEW

**Comment by salvadord** [comment]
Cliff, can you please make the PR to the development branch? thanks!

**Comment by cliffckerr** [comment]
Will do, give me a few hours!

**Comment by cliffckerr** [comment]
@salvadord done

**Comment by salvadord** [comment]
added changes manually to dev branch

**Pull request merged**
