### PR TITLE
allow function as input in textFields

### PR DESCRIPTION
**Pull request by rodriguez-facundo**
Adding a function to check if a string could be evaluated as function.
Also a minor modification to type in metadata

### CODE REVIEW

**Comment by jackdwyer** [comment]
I'd suggest using [callable](https://docs.python.org/3/library/functions.html#callable)
It is in python 2.x as well
```
def ValidateFunction(strFunc):
    return callable(strFunc)
```

**Comment by rodriguez-facundo** [comment]
Hi @jackdwyer, thanks for taking a look at it.

It seems callable only checks if the object has a __call__ method, so it will return True even if the evaluation returns False

**Comment by jackdwyer** [comment]
why can't a user provide a function that does return False?

my understanding for this PR is that you are only validating whether the
passed parameter is a string or a function. not its result.

**Comment by jackdwyer** [comment]
Is it that a user could define:
- a string
- an expression
- a function
?

**Comment by rodriguez-facundo** [comment]
In this case, the user will use the GUI to enter (in a textField) something like the following:

exp(2.7)*uniform(17, 39)*pre_x*dist_3D_border

so, in order to know if that is a valid string, I need to import the h module in neuron to have uniform(), and I need to declare pre_x and dist_3D_border. So, there are a couple things going on there.

Maybe the confusion comes from the fact that we are not using this in netpyne per se, but has a method to validate strings in the GUI frontend.

**Comment by rodriguez-facundo** [comment]
it is an expression... I put **function** in the title...   My bad

**Comment by jackdwyer** [comment]
ha no worries! thanks for the context it makes more sense 👍

**Pull request merged**
