### PR TITLE
Sonata

### PR DESCRIPTION
**Pull request by salvadord**

### CODE REVIEW

**Comment by salvadord** [comment]
@pgleeson I merged development into sonata, fixed a few issues and conflicts, and pushed to the sonata branch. I tested that it replicates the previous results: https://github.com/Neurosim-lab/netpyne/commit/752fabe5c553f05b92ad2d29fbb12744e297a138

 closing this PR.

**Comment by pgleeson** [comment]
@salvadord did you mean to close this PR (sonata branch into development)? The other one I opened (#419) is already merged, but the latest Sonata func is not in development

**Comment by salvadord** [comment]
thanks! was planning to merge but forgot in the end. will merge and release another version soon

**Comment by pgleeson** [comment]
No problem. Testing this branch merged in with neuroml and it seems to have added a change in the number of spikes generated by the M1 model (failure at this line: https://github.com/Neurosim-lab/netpyne/blob/edb67b5098b2e7923d55010ded59ad1bf75c0f18/examples/M1/M1_run.py#L7)

**Comment by salvadord** [comment]
@pgleeson - fixed, had to make allowing self connections also optional (cfg.allowSelfConns)

**Pull request merged**
