### PR TITLE
ran black on NetPyNE

### PR DESCRIPTION
**Pull request by joewgraham**

### CODE REVIEW

**Review by salvadord — APPROVED** [review]
All looks good! It almost duplicates the number of lines in the code, but agree that looks cleaner! Hopefully everything keeps working ok :)

**Comment by salvadord** [comment]
@joewgraham I was going to merge this but there's 3 conflicts, can you check them please? thx

**Comment by lakesare** [comment]
Just a heads-up - we're going to have 630 conflicts if we merge this PR prior to #623.
We should try to merge #623, and then run the black again.

**Comment by joewgraham** [comment]
I am closing this pull request and re-running black on the latest development branch.

**Comment by joewgraham** [comment]
I'm looking at your PR now and I'll merge it before I re-run Black.

**Pull request closed without merging**
