### PR TITLE
returning gid as identity of a cell

### PR DESCRIPTION
**Pull request by wwlytton**
I'm not really sure that this is the best label to use (gid) but seems better than current default which is meaningless.  eg <netpyne.cell.compartCell.CompartCell at 0x7f4e06eaaa90>
now returning:
In [7]: sim.net.cells[0].secs.soma.hObj.hname()
Out[7]: 'gid=0.soma'
In [8]: sim.net.cells[0].secs.soma.hObj.cell()
Out[8]: gid=0

Might be nice to have other info in the string as well e.g. cellType cellModel -- I didn't add them since wasn't sure if those are obligatory tags -- if they are then let me know and i'll put those in.  Problem with gid is that it seems that it's not obligatory for some reason?  If cellType cellModel available then I would also put these into the name=  

I also note that there is some debate online about the desirability of having __repr__ return __str__ but need that to get this string returned here

### CODE REVIEW

**Comment by salvadord** [comment]
@wwlytton nice feature!

yeah, all cells will have a cell gid, and most will have cellType (think this obligatory) and cell Model. So can check if the exist and if so return.

Also would be useful to keep the class name ('CompartCell') as there are other internal cell classes, such as PointCell.

**Comment by wwlytton** [comment]
ok now looks like this 
Out[9]: pointCell_NetStim_1200
Out[10]: compartCell_OLM_HH_800
wanted to use 'pop' instead of 'cellType' but that apparently doesn't exist at time of creation
cell.py still remains to be done -- i'll look into later

**Comment by wwlytton** [comment]
i get it: 'pop' not available since creating a type/model of cell that will be used in a population

**Comment by salvadord** [comment]
@wwlytton great! can you please add to CHANGES.md (https://github.com/Neurosim-lab/netpyne/blob/development/CHANGES.md) a bullet point for each change you made (bug fixes go at the end of the list) ? 

ps. you might need to merge the latest 'development' into your branch, since I made some changes yesterday.

**Pull request merged**
