### PR TITLE
Neuroml updates

### LINKED ISSUE #503: Neuroml needs to be adapted to the new simplified cellParams
- @pgleeson neuroml code giving an error with tuts+examples using new simplified cellParams so added try/except and removed from Travis

- @joewgraham let's make sure this is fixed before the release

### PR DESCRIPTION
**Pull request by pgleeson**
Fixes #503

A request too to revert this/development back to v0.9.7... Anywhere that tries to install this updated version will just ignore it if they've an earlier version calling itself v0.9.7...

### CODE REVIEW

**Comment by joewgraham** [comment]
I'm going through pull requests today.  It looks like this is good to go, but I wanted final confirmation.

@pgleeson , @salvadord

**Comment by pgleeson** [comment]
@joewgraham Yes, fine from my side...

**Comment by salvadord** [comment]
@pgleeson, in the development branch we've always kept he version number the same as in the latest release (ie. v0.9.6 in this case). I think temporarily we changed that to v0.9.7 by mistake, but then switched it back to 0.9.6.

Also, since neuroml was triggering errors due to the new simplified cellParams, I added a massive try/except block here: https://github.com/Neurosim-lab/netpyne/blob/de4f67a4a8986978020cb0524c9014bceba77a36/netpyne/conversion/neuromlFormat.py#L675 . I think it's a good failsafe in case something fails, but please check to see if you agree.

**Comment by pgleeson** [comment]
Happy to have that try/except block there...

**Comment by salvadord** [comment]
the last travis test is failing: python SimpleNet_import.py -nogui

so I just commented it out for now

**Comment by pgleeson** [comment]
Error with SimpleNet_import.py fixed now by increasing scope of try/except statement...

**Comment by joewgraham** [comment]
Thanks!  I'll incorporate this PR today.

**Comment by pgleeson** [comment]
Thanks for that, but please don't delete the branch... This is the stable "works with all my stuff" branch which is regularly tested with other nml tools and may at times be slightly out of sync with development...

**Pull request merged**
